# Generated by Django 5.2.8 on 2025-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if no file uploaded)', null=True),
        ),
    ]
