# Generated by Django 5.2.8 on 2025-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
